### PR TITLE
One more

### PR DESCRIPTION
**Pull request by znicholls**
@maritsandstad sorry I re-ran the notebook and saw that something is now not working with the emissions input (emissions appear to all go to zero in 2015, see screenshot below). I'm not sure what is going on, I am hoping you can fix it...

image

### CODE REVIEW

**Comment by maritsandstad** [comment]
Well, yes one can always hope... ;-) I'll be looking into it. Pretty sure it did work before, so I guess I'll get there in the end;-)

**Comment by znicholls** [comment]
So I updated and fixed the aerosol ERF problem but now the GHG problem is more obvious... 
image

**Comment by maritsandstad** [comment]
@znicholls : Looks like maybe the GHG emission are not read in correctly. Does this input file have the same units as the data we have used previously?

**Comment by znicholls** [comment]
It's the same as the tests, I don't think there's any change...

**Comment by znicholls** [comment]
It looks like the NOx conversions weren't working (not sure why that matters for GHGs but it seems to have fixed things).

The last thing (which I don't know how to test) is how the biomass burning aerosol vs. total split for e.g. BC and OC. The column headers are "BMB_AEROS_BC	BMB_AEROS_OC	BC	OC" but I think some double counting happens because e.g. total BC (incl. biomass burning) gets put in the BC column whereas I'm guessing it's not meant to be the total (looking at the 2014 values it certainly seems so).

**Comment by maritsandstad** [comment]
Hi @znicholls, So we've also found that we have a huge methane problem in the WGIII scenarioset. (The concentrations and forcing fall off a cliff in 2015 for all scenarios...) I'm not really sure what is going on, but one possibility is that the natural emission are being disregarded or something... Anyways, this may mean that I'm not really reading the inputs in correctly, and this might also be causing the the BC OC problem. So in the SCMData is the BC/ OC data given totals and not anthropogenic? In that case I might indeed be double counting  it, adding in biomass burning from from the preexisting file in addition to the total BC and OC emissions...

**Comment by maritsandstad** [comment]
Another reason things might be weird, is that I use ssp245 (the RCMIP-version) to fill in variables that are missing from the data... Is that perhaps dubious? What do you do for MAGICC?

**Comment by znicholls** [comment]
Bugger re methane bug! Hope you find a solution.

Re OC/BC in RCMIP. Yes they're totals. It's sort of messy because I've never found a historical data source which properly separates anthropogenic contributions from natural contributions (some biomass burning is from anthropogenic fires, some is not and no one seems to report the split, probably because it's almost impossible to estimate). If it makes you feel better, this also broke magicc initially.

**Comment by znicholls** [comment]
Re missing variables, we also infill using RCMIP but magicc expects those RCMIP totals. If the RCMIP totals don't match what cicero expects then you might have to be more careful.

**Comment by maritsandstad** [comment]
I think it is likely fine with the RCMIP totals...

However, I really don't understand the methane drop...

**Pull request merged**
