### PR TITLE
Unit conversion fixes

### PR DESCRIPTION
**Pull request by znicholls**
I've swapped to using openscm-units for the unit conversion, so things won't break every time a new unit is given. This also required updating some other places, and highlighted an ambiguity in the N2O unit labelling.

### CODE REVIEW

**Comment by znicholls** [comment]
@maritsandstad

**Comment by znicholls** [comment]
This PR fixes the N2O ambiguity which I refer to https://github.com/openscm/openscm-units/pull/25

**Comment by maritsandstad** [comment]
This is probably a very good fix. Just need to make sure I understand it properly, so it doesn't cause any new weird behavior... @znicholls, do you know why all the expected values shifted slightly for this update? I started the full WGIII dataset rerun last night, but should I then maybe redo it again after merging this PR in?

**Comment by znicholls** [comment]
> do you know why all the expected values shifted slightly for this update?

Rounding errors I believe. The conversions used by openscm-units are exact (e.g. 14/46), as compared to the decimal approximations that were used previously (e.g. 0.304). The ~0.1% change introduced by this propagates through to all the other results (which also change by ~0.1%).

**Comment by znicholls** [comment]
> I started the full WGIII dataset rerun last night, but should I then maybe redo it again after merging this PR in?

I wouldn't worry, 0.1% change isn't an issue and there'll be more runs to come in future.

**Comment by maritsandstad** [comment]
Ok, that makes sense! (After trying to chasing this bug down for a very frustrating more than a week, I'd like to know I have a bit more of a grasp of what's going on where in the code... I'll likely just forget by the time I need to go back, though...)

**Pull request merged**
