### PR TITLE
Review

### PR DESCRIPTION
**Pull request by znicholls**
@maritsandstad I read through https://github.com/openscm/openscm-runner/pull/24/files. These are the comments I made as I went. Can you have a read please and either implement fixes if the path looks clear or simply add a comment under the change if it doesn't? 

Having actually stepped through things now, I think overall things look pretty good. Given how Cicero-SCM works, I don't think there's a better way to parallelise it.

### CODE REVIEW

**Comment by maritsandstad** [comment]
@znicholls: For the testing of the parallel code, I had to have that in order to reach the 95% test coverage...

**Comment by maritsandstad** [comment]
Also, not me who produces the binary, so not sure I can make that Windows compatible. At least can't do that today...

**Comment by maritsandstad** [comment]
Otherwise, I think I've conformed to your comments now. Are we then moving on to the full pipeline?

**Comment by znicholls** [comment]
> @znicholls: For the testing of the parallel code, I had to have that in order to reach the 95% test coverage

Great thanks

> Also, not me who produces the binary, so not sure I can make that Windows compatible. At least can't do that today...

Ok that will be a problem eventually but not a blocker now (so not doing it today is fine). We should add a check of the user's operating system though. 

> Otherwise, I think I've conformed to your comments now.

Sorry have I missed something? The only change I've seen in response to this is https://github.com/openscm/openscm-runner/pull/24/commits/0faacb9585e64f140e7e9685a263eba169d23378. There's still some things in here which aren't done there, i.e. the fixes in `src/openscm_runner/adapters/ciceroscm_adapter/_run_ciceroscm_parallel.py` and the fixes and questions in `src/openscm_runner/adapters/ciceroscm_adapter/make_scenario_files.py`. You're welcome to start experimenting with the pipeline, but the suggested changes (and some fixes we will have to think through) will be needed before we merge https://github.com/openscm/openscm-runner/pull/24 into master because the suggested changes will a) make future maintenance way simpler and b) remove some patterns which are super slow.

**Comment by maritsandstad** [comment]
Oh, sorry will deal with those now, but I genuinely did not see them Yesterday. They were also somehow marked with a blue "New changes since last view" at your review commit this morning, so overall weird, I guess...

**Comment by znicholls** [comment]
> They were also somehow marked with a blue "New changes since last view" at your review commit this morning

You must have looked just between me pushing the first three and the last one. All good. Feel free to simply mark them if you want. As I said, they need to be sorted before we merge to master but they're not blockers if you want to start experimenting with the pipeline.

**Comment by maritsandstad** [comment]
I would very much like to speed up. But I can't seem to find out how to pull out the model and scenario from smdf without casting it....

**Comment by znicholls** [comment]
> But I can't seem to find out how to pull out the model and scenario from smdf without casting it

Ok cool leave that one for me, it's a little bit fiddly

**Comment by maritsandstad** [comment]
I think I managed... Probably not in a very fantastic way, but it seems to work...
model = smdf[2015].keys()[0][0]

**Comment by maritsandstad** [comment]
Ok, so now I think I dealt with most of the review comments. For the configurable number of workers in the parallel runs. I don't really understand how the whole config thing works, so I'll sit on that for a bit. 

Also for your TODO comment in the _run_magicc_parallell file, isort and black go into an infinite loop of disagreement if the comment stays where you put it, so I moved it a bit.

Finally, you put some question marks here and there, and I'm not sure what to do with those, but I checked the adjacent code.

**Comment by maritsandstad** [comment]
Yeah, and I keep the print statement on the config part in to not have to delete the imports of os and config for pylint to stop complaining...

**Comment by maritsandstad** [comment]
@znicholls, is there still lot's you think I have todo, or can I move on to the climate-assessment part?

**Pull request closed without merging**
