### PR TITLE
Re-run notebook

### PR DESCRIPTION
**Pull request by znicholls**
@maritsandstad this re-runs the notebook which should get the tests passing. Unfortunately no helpful insights re methane though...

### CODE REVIEW

**Comment by maritsandstad** [comment]
@znicholls: You added testing for a greenhouse gas ERF drop in 2015, though... Can I ask about that? So the test passes for the openscm_runner, but I assume you added it, because we had drops for the climate assessments, or is that not why? (I mean we do, caused by the methane issue...) Did we also have it in the runner?

**Comment by znicholls** [comment]
> Did we also have it in the runner?

Yep it was in the runner too, as identified in https://github.com/maritsandstad/openscm-runner/pull/9. So I think it's now fixed, but I obviously haven't checked with the climate assessment runs.

**Comment by znicholls** [comment]
If you run the example notebook, you should get output like 
image

That looks like things are working (at least in this setup...)

**Comment by znicholls** [comment]
Using 999e3f499fb9024164ee6260a8ea751f8ebfbe I get output like the below (so I think we've fixed whatever it was, feel free to add more tests as needed)

**Comment by maritsandstad** [comment]
@znicholls, I think maybe the last image didn't upload correctly...

**Comment by znicholls** [comment]
> @znicholls, I think maybe the last image didn't upload correctly

Ooops. Well it just had methane concentrations falling off a cliff after 2015

**Comment by maritsandstad** [comment]
Well, weirdly, methane concentrations falling off a cliff has become somewhat of an obsession of mine lately, so I'd actually really like to see the image @znicholls... Also if you have the faintest idea what solved the issue, I'm all ears...

**Comment by znicholls** [comment]
This is what it looked like 

image

It was solved by https://github.com/maritsandstad/openscm-runner/commit/a540c2bfdbbc6ed5a5ac79f28fc87a9dd349c4e4 i.e. fixing the NOx unit conversion (which meant that NOx emissions were way too high I think)

**Comment by maritsandstad** [comment]
Yes, this looks just like the type of nonsense I'm getting in the assessment... Thanks a bunch for the image and identifying the commit that fixes it... My guess would be that the formatting done in that fix was what fixed the methane issue, but that it possibly didn't fix it perfectly, so that the issue somehow is still occurring in the newer version when the data is fed in from the climate-assessment-pipeline... It's really weird, but at least I think I have a good lead on what to look for and maybe even how... Thanks again, and wish me luck, I guess ;-)

**Comment by znicholls** [comment]
> it possibly didn't fix it perfectly

So even with all these updates, it's still not right? Hmm sounds tricky.

Good luck!

**Comment by maritsandstad** [comment]
Thank you again, and I think I managed... Turned out the methane fix of a540c2b didn't work in the climate-assessment context as there NOx emissions are measured in units Mt NO2/yr. Of course that's the same, but the conversion didn't kick in for that, so the NOx error that caused the methane drop was still there for the climate-assessment runs.

**Pull request merged**
